# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: GitHub API Request
        # You may pin to the exact commit or the version.
        # uses: octokit/request-action@7e93b91076fad3920c29d44eb2a6311d929db3dd
        uses: octokit/request-action@v2.1.0
        env:
         GITHUB_TOKEN: ${{ secrets.UPDATER_TOKEN }}
        with:         
          # HTTP Verb + path as shown on https://developer.github.com/v3/
          route: PATCH /repos/{owner}/{repo}/actions/variables/MAIN_COUNTER
          repo: context.repo.repo
          owner: context.repo.owner
          name: context.repo.owner
          value: 2
          
                
